jobs:
  include:
    - stage: test
      script:
        - bash tests/test1.sh
    - stage: deploy      
      deploy:
        provider: releases
        api_key:
          secure: lV9MBti39/UPTXiqlv3c/OMSJvFaoLr+qcq0qAEkT1yeQaIU7EE5rljhVWKqY5k1FCn1ppOAOm0L627qdW0PvWtZAiadPr8l+d8iGLeYgrprIOPv8bUNk9hwdzWtjThdzmWuP+LrjKIgnSgp/XltJekL2bwmB7UA6LAZt+TA4JGhhLeGGyns4Aht6wInZCwD1TlPbXutSjBzFRrxNikZUTMkZNmYjhBmqPssX0EmCUeO/6fd8JiWKZt2VopzaN738t8ZTqtgF5x3ace0Djv391K10IZnZDvmUQdEEGat5cVY4cDjU47pKxUwZvpi9RPKWMlyThK5e3hetSVTfDj5UaqD8RwkmOKNuxRIAAYoLVqlzs8zdTglAEySQqXBg0CXaco08aV9NU44YIpy3vLtp/V3lUD5CLcA66oWbquxIJyr/oKDbc051xPOC97prnrEmeyUQvFt4YKpQEwwxYF1Di0tbFlt78IWU+YugWfNS3ohzKb2uMMyqvEH0w4yiudvo61f4eguGX6g6wI1WfQFcaWBLTnF6zZclCyMLQWncr656l0oc24vtOkjNMl9gQDXpRE6DlordNBb82nUkcZfR+GrpKn5EsWGwgfaKIjelhcK7t0stEChTl3FvClgmpeBR+tYPU6SvBvpjhCvhhPOV3z9+gIEMWDG/mzoAiOLuCE=
        on:
          repo: anthshor/shell-hello
